import Head from 'next/head';

export default function Index({
  title = 'Naples Next',
  content = 'Generated by naples next',
}) {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content={content} />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
